version: "3.8"

services:
  zeebe:
    image: camunda/zeebe:8.6.0
    container_name: zeebe
    ports:
      - "26500:26500"
      - "9600:9600"
    environment:
      - ZEEBE_LOG_LEVEL=debug
    volumes:
      - zeebe-data:/usr/local/zeebe/data

  operate:
    image: camunda/operate:8.6.0
    container_name: operate
    ports:
      - "8081:8080"
    environment:
      - CAMUNDA_OPERATE_ZEEBE_GATEWAYADDRESS=zeebe:26500
      - CAMUNDA_OPERATE_ELASTICSEARCH_URL=http://elasticsearch:9200
    depends_on:
      - zeebe
      - elasticsearch

  tasklist:
    image: camunda/tasklist:8.6.0
    container_name: tasklist
    ports:
      - "8082:8080"
    environment:
      - CAMUNDA_TASKLIST_ZEEBE_GATEWAYADDRESS=zeebe:26500
      - CAMUNDA_TASKLIST_ELASTICSEARCH_URL=http://elasticsearch:9200
    depends_on:
      - zeebe
      - elasticsearch

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.9.0
    container_name: elasticsearch
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      # HIER ÄNDERN! Erhöhen Sie den Wert auf mindestens 1024m (1 GB) oder 2g (2 GB)
      - ES_JAVA_OPTS=-Xms1g -Xmx1g  # <= Empfohlene Änderung
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data


volumes:
  zeebe-data:
  elasticsearch-data: